name: CMake-build

on:
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: ${{ matrix.config_type }}

jobs:
  build:
    # Use matrix to specify OS and build type.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config_type: ["Debug", "Release"]
        
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workdpace}}/src -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/SimpleProject.*
      