name: CMake-build

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    # Use matrix to specify OS and build type.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config_type: ["Debug", "Release"]
        
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/src -DCMAKE_BUILD_TYPE=${{matrix.config_type}}
      
    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config_type}}
    
    - uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: ${{github.workspace}}/build/${{matrix.config_type}}/SimpleProject.*
      